import { defaultSchema } from 'hast-util-sanitize'
import type { Schema as SanitizeSchema } from 'hast-util-sanitize'

/**
 * hast-util-sanitize does not re-export PropertyDefinition from its root, so
 * it is derived from the Schema type rather than restated here - a hand-written
 * copy drifts from upstream and is narrower than the real thing.
 */
type PropertyDefinition = NonNullable<
  NonNullable<SanitizeSchema['attributes']>[string]
>[number]

/**
 * The trust boundary.
 *
 * Everything before `rehype-sanitize` in the pipeline is user-controlled: the
 * markdown itself, and any raw HTML embedded in it. Everything after is
 * generated by us from an already-sanitised tree - KaTeX output, Shiki
 * highlighting, Mermaid placeholders - and is therefore trusted.
 *
 * This ordering is the whole design. Running the sanitizer last would force
 * us to whitelist `style=`, `<svg>`, `<math>`, `<annotation>` and dozens of
 * KaTeX class names, which is a large permissive surface that also happens to
 * be exactly what an attacker would want. Instead the sanitizer sees only
 * plain markdown-shaped HTML, and the generators run downstream of it.
 *
 * So the extensions below are deliberately narrow: they permit the *marker*
 * classes the downstream plugins look for, and nothing else.
 */

/** Classes remark-math emits and rehype-katex consumes. */
const MATH_CLASSES = ['math', 'math-inline', 'math-display'] as const

/** Language classes on code blocks, consumed by Shiki and the Mermaid pass. */
const CODE_LANGUAGE_PATTERN = /^language-[a-z0-9+#.-]+$/i

/** GFM alert callout classes from remark-github-blockquote-alert. */
const ALERT_CLASSES = [
  'markdown-alert',
  'markdown-alert-note',
  'markdown-alert-tip',
  'markdown-alert-important',
  'markdown-alert-warning',
  'markdown-alert-caution',
  'markdown-alert-title',
] as const

const base = defaultSchema

/** The upstream schema's own allowances for a tag, so we extend rather than replace. */
const inherited = (tag: string): PropertyDefinition[] => [
  ...(base.attributes?.[tag] ?? []),
]

/**
 * The upstream allowances for a tag, minus named properties we intend to
 * re-declare with a value allowlist.
 *
 * This matters more than it looks. hast-util-sanitize permits an attribute if
 * *any* of its definitions match, and a bare `'src'` string matches every
 * value. Adding `['src', /regex/]` alongside an inherited bare `'src'`
 * therefore constrains nothing at all - the permissive entry wins. The
 * restrictive definition only bites once the bare one is removed.
 */
const inheritedExcept = (tag: string, drop: readonly string[]): PropertyDefinition[] =>
  inherited(tag).filter((def) => {
    const name = typeof def === 'string' ? def : def[0]
    return !drop.includes(name)
  })

/**
 * A class allowance: `['className', ...permitted]`.
 *
 * Written as a helper because the tuple's first element must be the property
 * name and TypeScript will not infer that shape from a plain array literal.
 */
const classes = (...allowed: (string | RegExp)[]): PropertyDefinition => [
  'className',
  ...allowed,
]

export const sanitizeSchema: SanitizeSchema = {
  ...base,

  tagNames: [
    ...(base.tagNames ?? []),
    // GFM tables and footnotes need the full table set plus <section>.
    'section',
    // Figures are how images are presented; the default schema omits them.
    'figure',
    'figcaption',
  ],

  attributes: {
    ...base.attributes,

    // Heading anchors, footnote targets and callout wrappers all need ids.
    //
    // `className` is deliberately NOT here. A bare 'className' on '*' is the
    // same trap `inheritedExcept` documents for `src`: it matches every value,
    // so it grants arbitrary attacker-supplied classes on every tag the
    // upstream schema does not already narrow - 43 of the 56 permitted tags,
    // including h1, h3-h6, em, strong, table, img, figure and details. That is
    // enough to restyle or spoof content using the reader's own stylesheet.
    // Classes are granted per tag below instead; the upstream schema already
    // carries precise allowances for the GFM footnote and task-list markup.
    '*': [...inherited('*'), 'id'],

    code: [...inherited('code'), classes(CODE_LANGUAGE_PATTERN, ...MATH_CLASSES)],
    pre: [...inherited('pre'), classes(CODE_LANGUAGE_PATTERN, 'mermaid')],
    span: [...inherited('span'), classes(...MATH_CLASSES)],
    div: [...inherited('div'), classes(...MATH_CLASSES, ...ALERT_CLASSES)],
    p: [...inherited('p'), classes(...ALERT_CLASSES)],
    blockquote: [...inherited('blockquote'), classes(...ALERT_CLASSES)],

    // Relative image paths are rewritten to blob URLs after sanitization, so
    // src must survive - but as an explicit value allowlist, not a bare
    // 'src'. A scheme-only check passes `data:text/html;base64,<script>`,
    // because the sanitizer validates the scheme and not the media type.
    // Listing the permitted shapes is what actually closes that.
    img: [
      ...inheritedExcept('img', ['src', 'srcSet', 'srcset']),
      [
        'src',
        /^https?:\/\//i,
        /^blob:/i,
        // Raster data URIs only. SVG is excluded: it is a document format
        // that can carry script, and nothing needs it inlined here.
        /^data:image\/(?:png|jpeg|jpg|gif|webp|avif|bmp);/i,
        // Relative paths, resolved against the asset map downstream.
        /^(?!\w+:)[^\s]+$/,
      ] as PropertyDefinition,
      'alt',
      'title',
      'width',
      'height',
      'loading',
    ],
    a: [...inherited('a'), 'href', 'title', 'id', 'dataFootnoteRef', 'ariaDescribedby'],

    // Task list checkboxes. Values are pinned, so nothing else gets through.
    input: [
      ['type', 'checkbox'] as PropertyDefinition,
      ['disabled', true] as PropertyDefinition,
      ['checked', true] as PropertyDefinition,
    ],

    th: [...inherited('th'), 'colSpan', 'rowSpan'],
    td: [...inherited('td'), 'colSpan', 'rowSpan'],
  },

  // Only these schemes may appear in a URL attribute. This is what stops
  // `javascript:`, `vbscript:` and `data:text/html` payloads.
  protocols: {
    ...base.protocols,
    href: ['http', 'https', 'mailto', 'tel', 'irc', 'ircs', 'xmpp'],
    // Belt and braces with the img value allowlist above: this rejects the
    // scheme, that rejects the media type.
    src: ['http', 'https', 'blob', 'data'],
  },

  // Never allowed, whatever the markdown says. Listing them explicitly rather
  // than relying on the default is deliberate: it documents the intent and
  // survives a future change to the upstream default schema.
  strip: ['script', 'style', 'iframe', 'object', 'embed', 'link', 'meta', 'base', 'form'],

  clobberPrefix: 'user-content-',
  clobber: ['name', 'id'],
}

/*
 * There is deliberately no second, server-side schema here.
 *
 * An earlier `printSchema` claimed to be "applied server-side before the print
 * service hands HTML to Chromium". It was never imported by anything, and it
 * could not have been: it extended `sanitizeSchema`, which by design forbids
 * `style=`, `<svg>` and `<math>` - precisely the trusted output that KaTeX,
 * Shiki and Mermaid generate downstream of the boundary. Running it over an
 * export strips the maths, the highlighting and every inline style, cutting a
 * representative document from 1297 to 499 bytes. A defence that cannot be
 * switched on is worse than none, because the comment describing it reads like
 * a control that exists.
 *
 * Re-sanitising after the generators is the same mistake the header of this
 * file rejects: it would force an allowlist for `style`, `<svg>`, `<math>` and
 * every KaTeX class, which is the large permissive surface the pipeline order
 * exists to avoid.
 *
 * What actually constrains the print path, in `server/`:
 *   - `javaScriptEnabled: false` on the browser context (`pdf.ts`), so script
 *     in a posted payload never executes;
 *   - `harden()` aborts every request whose URL is not `data:`, `blob:` or
 *     `about:` (`pdf.ts`), so no subresource is fetched;
 *   - `serviceWorkers: 'block'` (`pdf.ts`);
 *   - a body limit on the endpoint (`index.ts`).
 *
 * If a server-side content filter is ever wanted, it needs its own schema
 * built for post-boundary markup - not a re-use of the pre-boundary one - plus
 * `hast-util-sanitize` and an HTML parser moved into runtime dependencies.
 */
